CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT as IDENTITY,
    name text NOT null CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS chronometers(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT as IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    hous integer NOT NULL,
    mins integer NOT NULL,
    secs integer NOT NULL,
    projectid integer REFERENCES projects(id)
);


-- data para la tabla projects
INSERT INTO projects (name, priority, description, deliverydate)
        values ('prueba 1', 1, 'solo para tener algo de data', '2022-03-3');

-- dara para la tabla chronometers
INSERT INTO chronometers (name, hous, mins, secs, projectid)
        values ('primera tarea', 4, 30, 50, 1);